#!/bin/sh
### notes on personalization ###
### in weatherurl, change metric to 1 to use Celcius or 2 if for Fahrenheit
### do not exceed 12 characters for greeting

### personalize these variables ###
firstline='This is a Private Server, unauthorized access will be prosecuted'
weathercity='Agadir'
weatherurl='http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=Agadir'

### colors ###
color1='\033[1;31m'  # light red
color2='\033[0;31m'  # red
color3='\033[1;32m'  # light green
color4='\033[0;32m'  # green
color5='\033[1;34m'  # light blue
color6='\033[0;34m'  # blue        
color7='\033[1;35m'  # light purple
color8='\033[0;35m'  # purple      
color9='\033[1;36m'  # light cyan  
color10='\033[0;36m'  # cyan       
color11='\033[0;37m'  # light grey 
color12='\033[1;37m'  # white      
color13='\033[0;33m'  # brown      
color14='\033[1;33m'  # yellow     
color15='\033[0;30m'  # black
color16='\033[1;30m'  # dark gray
nocolor='\033[0m'    # no color

### banner ###
figlet "               E M C" -f small
printf "${color1}${firstline} ${nocolor}\n"
printf "${color14}Hostname: $(hostname) ${nocolor}\n"
printf "${color14}System OS: `lsb_release -s -d`${nocolor}\n"
printf "${color14}`uname -srmo`${nocolor}\n"
printf "Weather (${weathercity}): `curl -s "${weatherurl}" | sed -n '/Currently:/ s/.*: \(.*\): \([0-9]*\)\([CF]\).*/\2°\3, \1/p'`\n"
printf "External IP: ${color9}`/usr/bin/wget -q -O - http://ipv4.icanhazip.com/ | /usr/bin/tail` ${nocolor}\n"
printf "Uptime: ${color4} `/usr/bin/uptime -p`  ${nocolor}\n"
memory_usage=`free -m | awk '/Mem:/ { printf("%3.1f%%", $3/$2*100) }'`
processes=`ps aux | wc -l`
printf "Memory Usage:\t%s\n" $memory_usage
printf "Processes: \t%s\n" $processes

#printf "               ${color1}   ${nocolor}\n"
